api:
    resource: '.'
    type:     'api_platform'
    #prefix:   /v1

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'

api_login_check:
    path: /login_check

gesdinet_jwt_refresh_token:
    path:     /auth/refresh-token
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"